env:
  account:
  region: eu-west-2

githubRepoOwner:
githubRepoName:

dev:
  stackName: projectname-dev-stack
  environmentType: dev
  branchName: master
  pipelineConfig:
    name: projectname-dev
    artifactsBucket: codepipeline-eu-west-2-975428383503
  s3Config:
    bucketName: projectname-dev-bucket
    publicAccess: false
    indexFile: index.html
    errorFile: index.html
