env:
  account:
  region: eu-west-2

githubRepoOwner: theaimegroup
githubRepoName: repoName

dev:
  stackName: projectname-dev-stack
  environmentType: dev
  branchName: main
  pipelineConfig:
    name: projectname-dev
    artifactsBucket: codepipeline-eu-west-2-975428383503
  s3Config:
    bucketName: projectname-dev-bucket
    publicAccess: true
    indexFile: index.html
    errorFile: index.html
